# Site Settings
title: "Jinttai's Space"
description: "Blog, Portfolio & Personal Notes"
url: "https://jinttai.github.io"
baseurl: ""
author:
  name: "jinttai"

# Build Settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio-item"

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
